# Resilience Config

circuit_breaker:
  failure_threshold: 5
  success_threshold: 2
  timeout: 10

resilience:
  retry:
    max_retries: 3
    base_backoff: 100ms
    rate_limiter:
      rps: 100
      burst: 10
    circuit_breaker:
      max_requests: 5
      interval: 60s
      timeout: 30s
      consecutive_failures: 3
      failure_rate_threshold: 0.5
