resilience:
  max_retries: 3
  base_backoff: 100ms
  bulkhead:
    capacity: 5
    timeout: 10s
  circuit_breaker:
    failure_rate_threshold: 0.5
    failure_threshold: 5
    success_threshold: 2
    consecutive_failures: 3
    max_requests: 5
    interval: 60s
    timeout: 30s
  rate_limiter:
    rps: 100
    burst: 10
